--------------------------------------------------------
--  File created - קועגונד-ÿםגאנÿ-26-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CPU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."CPU_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."MEMORY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTEBOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."NOTEBOOK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTEBOOKS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."NOTEBOOKS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SALES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."SALES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STORE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."STORE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."USERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VENDOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTEBOOK"."VENDOR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CPU
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."CPU" 
   (	"ID" NUMBER, 
	"FREQUENCY" FLOAT(126), 
	"MODEL" VARCHAR2(30 BYTE), 
	"VENDOR_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMORY
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."MEMORY" 
   (	"ID" NUMBER, 
	"VOLUME" NUMBER, 
	"VENDOR_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTEBOOK
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."NOTEBOOK" 
   (	"ID" NUMBER, 
	"MODEL" VARCHAR2(30 BYTE), 
	"MANUFACTURE_DATE" DATE, 
	"CPU_ID" NUMBER(19,0), 
	"MEMORY_ID" NUMBER(19,0), 
	"VENDOR_ID" NUMBER(19,0), 
	"MANUFACTURE_DATES" DATE, 
	"MODELS" VARCHAR2(255 CHAR), 
	"PRICES" FLOAT(126), 
	"SERIALS" VARCHAR2(255 CHAR), 
	"VENDORS" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTEBOOKS
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."NOTEBOOKS" 
   (	"ID" NUMBER(19,0), 
	"MANUFACTURE_DATES" DATE, 
	"MODELS" VARCHAR2(255 CHAR), 
	"PRICES" FLOAT(126), 
	"SERIALS" VARCHAR2(255 CHAR), 
	"VENDORS" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."SALES" 
   (	"ID" NUMBER, 
	"SALES_DATE" DATE, 
	"SALES_QUANTITY" NUMBER, 
	"STORE_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."STORE" 
   (	"ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRICE" FLOAT(126), 
	"PRISEFORONE" FLOAT(126), 
	"NOTEBOOK_ID" NUMBER(19,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."USERS" 
   (	"ID" NUMBER, 
	"LOGINS" VARCHAR2(20 BYTE), 
	"PASSWORDS" VARCHAR2(20 BYTE), 
	"DATES_REGISTRATION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENDOR
--------------------------------------------------------

  CREATE TABLE "NOTEBOOK"."VENDOR" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into NOTEBOOK.CPU
SET DEFINE OFF;
Insert into NOTEBOOK.CPU (ID,FREQUENCY,MODEL,VENDOR_ID) values ('1','2,7','i5','2');
REM INSERTING into NOTEBOOK.MEMORY
SET DEFINE OFF;
Insert into NOTEBOOK.MEMORY (ID,VOLUME,VENDOR_ID) values ('6','8','1');
Insert into NOTEBOOK.MEMORY (ID,VOLUME,VENDOR_ID) values ('7','8','1');
REM INSERTING into NOTEBOOK.NOTEBOOK
SET DEFINE OFF;
Insert into NOTEBOOK.NOTEBOOK (ID,MODEL,MANUFACTURE_DATE,CPU_ID,MEMORY_ID,VENDOR_ID,MANUFACTURE_DATES,MODELS,PRICES,SERIALS,VENDORS) values ('5','Aspire',to_date('10.10.14','DD.MM.RR'),'1','7','1',null,null,null,null,null);
REM INSERTING into NOTEBOOK.NOTEBOOKS
SET DEFINE OFF;
REM INSERTING into NOTEBOOK.SALES
SET DEFINE OFF;
REM INSERTING into NOTEBOOK.STORE
SET DEFINE OFF;
REM INSERTING into NOTEBOOK.USERS
SET DEFINE OFF;
Insert into NOTEBOOK.USERS (ID,LOGINS,PASSWORDS,DATES_REGISTRATION) values ('2','w','w',to_date('24.01.17','DD.MM.RR'));
Insert into NOTEBOOK.USERS (ID,LOGINS,PASSWORDS,DATES_REGISTRATION) values ('3','wee','wee',to_date('24.01.17','DD.MM.RR'));
Insert into NOTEBOOK.USERS (ID,LOGINS,PASSWORDS,DATES_REGISTRATION) values ('4','2','2',to_date('24.01.17','DD.MM.RR'));
Insert into NOTEBOOK.USERS (ID,LOGINS,PASSWORDS,DATES_REGISTRATION) values ('1','s','s',null);
REM INSERTING into NOTEBOOK.VENDOR
SET DEFINE OFF;
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('8','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('9','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('10','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('6','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('7','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('1','Samsung');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('2','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('3','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('4','Intel');
Insert into NOTEBOOK.VENDOR (ID,NAME) values ('5','Intel');
--------------------------------------------------------
--  DDL for Index STORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."STORE_PK" ON "NOTEBOOK"."STORE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTEBOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."NOTEBOOK_PK" ON "NOTEBOOK"."NOTEBOOK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."MEMORY_PK" ON "NOTEBOOK"."MEMORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CPU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."CPU_PK" ON "NOTEBOOK"."CPU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."SALES_PK" ON "NOTEBOOK"."SALES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VENDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTEBOOK"."VENDOR_PK" ON "NOTEBOOK"."VENDOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."SALES" ADD CONSTRAINT "SALES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTEBOOK"."SALES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."SALES" MODIFY ("SALES_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."SALES" MODIFY ("SALES_QUANTITY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMORY
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."MEMORY" ADD CONSTRAINT "MEMORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTEBOOK"."MEMORY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."MEMORY" MODIFY ("VOLUME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VENDOR
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."VENDOR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."VENDOR" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."VENDOR" ADD CONSTRAINT "VENDOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CPU
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."CPU" ADD CONSTRAINT "CPU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTEBOOK"."CPU" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."CPU" MODIFY ("FREQUENCY" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."CPU" MODIFY ("MODEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTEBOOKS
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."NOTEBOOKS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOKS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTEBOOK
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."NOTEBOOK" ADD CONSTRAINT "NOTEBOOK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOK" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOK" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOK" MODIFY ("MANUFACTURE_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."STORE" ADD CONSTRAINT "STORE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTEBOOK"."STORE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."STORE" MODIFY ("QUANTITY" NOT NULL ENABLE);
 
  ALTER TABLE "NOTEBOOK"."STORE" MODIFY ("PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CPU
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."CPU" ADD CONSTRAINT "FK_20LVOBWIAE7UH9M0TTOQ8EAYH" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "NOTEBOOK"."VENDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMORY
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."MEMORY" ADD CONSTRAINT "FK_34T3FUA2AGUGNB143UWBYOT96" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "NOTEBOOK"."VENDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTEBOOK
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."NOTEBOOK" ADD CONSTRAINT "FK_57K3XDKSA3EEB9WSF22PS4UTI" FOREIGN KEY ("CPU_ID")
	  REFERENCES "NOTEBOOK"."CPU" ("ID") ENABLE;
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOK" ADD CONSTRAINT "FK_79MHH4PVX3FGUTVSOYQLSL5XQ" FOREIGN KEY ("VENDOR_ID")
	  REFERENCES "NOTEBOOK"."VENDOR" ("ID") ENABLE;
 
  ALTER TABLE "NOTEBOOK"."NOTEBOOK" ADD CONSTRAINT "FK_E498S3OUSY7K4FLQE3YOIKR2X" FOREIGN KEY ("MEMORY_ID")
	  REFERENCES "NOTEBOOK"."MEMORY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."SALES" ADD CONSTRAINT "FK_20LKQNMFOC1UCRL3BUM2K8SUK" FOREIGN KEY ("STORE_ID")
	  REFERENCES "NOTEBOOK"."STORE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "NOTEBOOK"."STORE" ADD CONSTRAINT "FK_3XIEKAGNBD41KADK7PFP6C2X7" FOREIGN KEY ("NOTEBOOK_ID")
	  REFERENCES "NOTEBOOK"."NOTEBOOK" ("ID") ENABLE;
